# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('cidade', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Contato de Empresa',
                'verbose_name_plural': 'Contatos de Empresa',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagas', models.IntegerField(null=True)),
                ('valor', models.IntegerField()),
                ('descricao', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='EtapaNegociacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Etapa de Negociação',
                'verbose_name_plural': 'Etapas de Negociação',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.Empresa'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='etapa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.EtapaNegociacao'),
        ),
        migrations.AddField(
            model_name='contato',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.Empresa'),
        ),
    ]
