# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 17:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefone', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('cidade', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagas', models.IntegerField(null=True)),
                ('valor', models.IntegerField()),
                ('descricao', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EtapaNegociacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.Empresa'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='etapa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.EtapaNegociacao'),
        ),
        migrations.AddField(
            model_name='contato',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.Empresa'),
        ),
    ]
