# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(max_length=256, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(max_length=512, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(max_length=128, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='etapanegociacao',
            name='descricao',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='etapanegociacao',
            name='etapa',
            field=models.CharField(max_length=128),
        ),
    ]
