# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='nome',
        ),
    ]
