# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Aplicação',
                'verbose_name_plural': 'Aplicações',
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('cidade', models.CharField(blank=True, max_length=20)),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('escolaridade', models.TextField(blank=True, null=True, verbose_name='Escolaridade')),
                ('experiencia', models.TextField(blank=True, null=True, verbose_name='Experiência')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('linkedin', models.URLField(blank=True, max_length=50)),
                ('github', models.URLField(blank=True, max_length=50)),
                ('cv', models.FileField(null=True, upload_to='candidato_cv/%Y/%m/%d/', verbose_name='Curriculum Vitae')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.CreateModel(
            name='EtapaRecrutamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Etapa de Recrutamento',
                'verbose_name_plural': 'Etapas de Recrutamento',
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('documento', models.FileField(null=True, upload_to='vaga_documentos/%Y/%m/%d/', verbose_name='Documento Original')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.Empresa')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutamento.Candidato'),
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutamento.EtapaRecrutamento'),
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutamento.Vaga'),
        ),
        migrations.AlterUniqueTogether(
            name='aplicacao',
            unique_together=set([('vaga', 'candidato')]),
        ),
    ]
