# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 15:45
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('cidade', models.CharField(blank=True, max_length=20)),
                ('linkedin', models.URLField(blank=True, max_length=50)),
                ('github', models.URLField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EstagioRecrutamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='candidatura',
            name='estagio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutamento.EstagioRecrutamento'),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutamento.Vaga'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='candidaturas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutamento.Candidatura'),
        ),
    ]
