# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='candidaturas',
        ),
        migrations.AddField(
            model_name='candidatura',
            name='candidato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recrutamento.Candidato'),
            preserve_default=False,
        ),
    ]
