# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='area_interesse',
            field=models.TextField(blank=True, null=True, verbose_name='Área(s) de interesse'),
        ),
    ]
