# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0002_candidato_area_interesse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='candidato',
            name='anexo1',
            field=models.FileField(blank=True, null=True, upload_to='candidato_anexo/%Y/%m/%d/_1/', verbose_name='Anexo 1 (Arquivo)'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='anexo2',
            field=models.FileField(blank=True, null=True, upload_to='candidato_anexo/%Y/%m/%d/_2/', verbose_name='Anexo 2 (Arquivo)'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='anexo3',
            field=models.FileField(blank=True, null=True, upload_to='candidato_anexo/%Y/%m/%d/_3/', verbose_name='Anexo 3 (Arquivo)'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='anexo4',
            field=models.FileField(blank=True, null=True, upload_to='candidato_anexo/%Y/%m/%d/_4/', verbose_name='Anexo 4 (Arquivo)'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='anexo5',
            field=models.FileField(blank=True, null=True, upload_to='candidato_anexo/%Y/%m/%d/_5/', verbose_name='Anexo 5 (Arquivo)'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='idade',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Idade'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='pretensao_salarial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Pretensão Salarial'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='candidato_cv/%Y/%m/%d/', verbose_name='Curriculum Vitae'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='github',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='linkedin',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='vaga_documentos/%Y/%m/%d/', verbose_name='Documento Original'),
        ),
    ]
