# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0003_auto_20180428_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Vaga Ativa (Sim/Não)'),
        ),
    ]
