# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recrutamento', '0004_vaga_ativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='ativa',
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='funcionario_conduzindo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Funcionário conduzindo aplicação'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='funcionario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Funcionário Responsável pela vaga'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('Ativa', 'ATIVA'), ('Em negociação com cliente', 'EM_NEGOCIACAO'), ('Inativa', 'INATIVA'), ('Paralisada', 'PARALISADA')], default='Ativa', max_length=128, verbose_name='Status da Vaga'),
        ),
    ]
