# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0006_auto_20180428_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('Ativa', 'ATIVA'), ('Em negociação com cliente', 'EM_NEGOCIACAO_CLIENTE'), ('Fechada', 'FECHADA'), ('Inativa', 'INATIVA'), ('Paralisada', 'PARALISADA')], default='Ativa', max_length=128, verbose_name='Status da Vaga'),
        ),
    ]
